telosnetwork/teloscan

- src/components/ContractSource.vue
- list filenames above source code
- list comp target first
> feat: list file name headers with comp target at top

- src/pages/Endpoints.vue
> fix: stack endpoint info on mobile

- src/css/app.scss
- src/css/dataCard.scss
subtle .css changes to margins, padding, balance & table
> @dummy subtle ui change + responsive

- src/css/app.scss
fix small discrepancy in padding when changing from dark to light theme
> @dummy dark theme discrepancy padding fix

- src/components/ConnectButton.vue
Adds chain to login data
On page load, does not try to autologin if chain is different from stored login data
> Stop autologin if chain is different

- src/components/AddressField.vue
- src/components/Transaction/LogsTable.vue
- src/components/Transaction/LogsTableRow.vue
- src/components/Transaction/LogsViewer.vue
- src/components/TransactionTable.vue
- src/css/app.sass
- src/events_overrides.json
- src/layouts/MainLayout.vue
- src/lib/Contract.js
- src/lib/ContractManager.js
- src/pages/Transaction.vue
- src/router/routes.js
- src/signatures_overrides.json
> Logs fixes, misc fixes, styling & optimizations

- src/pages/Transaction.vue
> Fixed trying to access null variable in trx page

- src/boot/q-component-defaults.js
Changed touch detection script with the same method Modernizer uses
Fixes #164
> Tooltip fade fix

- src/pages/Endpoints.vue
Fixes broken endpoint page, adds error message for failed endpoints and highlighs with green/yellow/red for endpoints behind HEAD block
> Fix endpoint page

- src/components/TransactionTable.vue
- src/layouts/MainLayout.vue
#189: The to addresses on transactions table (account page & transactions page) had several problems, including: being tagged as contract when they shouldn't, not loading the name on navigation, etc....
#191: The menu links for mainnet / testnet were wrong
Checked different account & transactions pages to make sure the to addresses showed correctly
Checked the menu on testnet & mainnet to make sure the correction worked
-   [x] I have checked my code and corrected any …
> Transactions table & Menu link fixes

- src/components/ContractTab/FunctionInterface.vue
- src/components/TokenList.vue
- src/lib/token-utils.js
- src/pages/staking/StakeForm.vue
- src/pages/staking/staking-utils.js
TODO add error banner notification for failed adds
This PR adds a link to each token in the token list to add it to metamask and updates the overall token list style a bit. Also fixes #234
__On a desktop client with Metamask installed:__
- go to any address' token list, e.g. http://localhost:8080/address/0x160505F3dfD1cb58B91e322c828Ae0F74c043c3C#tokens
- the layout of the token list should be reasonable and clean
- there should be a link to add token to metamask
- click the Metamask link
- a MM window should open asking to track the correct token
__On a mobile client in the browser:__
- go to any address' token list, e.g. `http://[your IP]:8080/address/0x160505F3dfD1cb58B91e322c828Ae0F74c043c3C#tokens`
- the layout of the token list should be reasonable and clean
- there should be a link …
> 212 | Add 'add token to metamask' link

- README.md
- Includes latest release badge to README.md
- Includes link to latest release
> Include release badge to README.md

- src/components/AddressField.vue
- src/components/ConfirmationDialog.vue
- src/components/ContractTab/FunctionInterface.vue
- src/components/ContractTab/GenericContractInterface.vue
- src/components/Health/Monitor.vue
- src/css/quasar.variables.sass
- src/lib/token-utils.js
- src/pages/AccountAddress.vue
- src/pages/staking/StakingFormInput.vue
Deleted $red, $green & $yellow from CSS
Replaced $red, $green & $yellow with $negative, $positive, $warning in vue files
-   [x] Visit the website and use the inspector to check that colored elements all have the right class (text-negative, background-negative, text-positive, ....)
> Removed duplicate colors

- LICENSE.md
- README.md
- Includes Apache license to this repo
- Includes badge to README.md
> Add Apache license

- src/components/Health/Monitor.vue
- src/components/header/AppHeader.vue
- src/layouts/MainLayout.vue
-   [x] I have included all english text to the translation file
-   [x] I have created a new issue with the required translations for the currently supported languages
> 331 strange behavior between mainnet and testnet

- src/i18n/en-us/index.js
- src/i18n/es-es/index.js
- src/pages/staking/UnstakeForm.vue
- test/pages/staking/__snapshots__/StakingFormInput.test.js.snap
This PR updates staking text per the issue, replacing missing i18n and updating language.
- go to https://deploy-preview-340--teloscan-stage.netlify.app/staking#unstake
- log in 
- input any amount and click Unstake
- verify missing translation is now present
-   [x] I have included all english text to the translation file
-   [x] I have created a new issue …
> #320 | Update staking text

- src/components/ConfirmationDialog.vue
- src/components/header/LanguageSwitcherModal.vue
- src/pages/staking/StakeForm.vue
- test/pages/staking/__snapshots__/StakeForm.test.js.snap
This PR fixes some style issues with light/dark mode, as well as fixes a missing translation
- go to https://deploy-preview-363--teloscan-stage.netlify.app/
- enable **light mode**
- log in using an account with a nonzero TLOS balance (or get funds from faucet)
- go to https://deploy-preview-363--teloscan-stage.netlify.app/staking
- enter any amount into the staking input and click Stake
- in the dialog that appears, the unstake period should be visible
- close the dialog
- open the language switcher (header > advanced > language)
- click the dropdown
- the selected language should be purple
- close dialogue and enable **dark mode**
- re-open the language switcher and click the dropdown
- selected language should still be purple
- switch back to **light mode**
- go to an unverified …
> #359 | Misc. style issues

- src/index.template.html
> Add fathom analytics

- src/components/ContractTab/FunctionInterface.vue
- src/components/ContractTab/GenericContractInterface.vue
- src/components/header/AppHeader.vue
- src/i18n/de-de/index.js
- src/i18n/en-us/index.js
- src/i18n/es-es/index.js
- src/i18n/fr-fr/index.js
- src/i18n/pt-br/index.js
See issues
1. While disconnected, navigate to an [unverified contract](https://deploy-preview-482--dev-mainnet-teloscan.netlify.app/address/0x29Bbb50A7314D7E0eA898eC33c025A93F8bC8153#contract)
2. See 'Use ERC1155 ABI' option
3. Select 'Read' and execute (while disconnected)
4. Select 'Write' see disabled
5. Connect wallet
6. Execute 'Write' action 
7. 'Sign in' and 'Sign out' button should say 'Connect Wallet' and 'Disconnect'
-   [x] I have checked my code and corrected …
> Enable 1155 ABI, execute read actions if disconnected

- src/i18n/de-de/index.js
- src/i18n/en-us/index.js
- src/i18n/es-es/index.js
- src/i18n/fr-fr/index.js
- src/i18n/pt-br/index.js
Updates cloud wallet notification copy
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
> fix: update cloud wallet notification

- src/components/ContractTab/function-interface-utils.js
- src/components/inputs/BytesArrayInput.vue
- src/i18n/de-de/index.js
- src/i18n/en-us/index.js
- src/i18n/es-es/index.js
- src/i18n/fr-fr/index.js
- src/i18n/pt-br/index.js
- test/components/ContractTab/function-interface-utils.test.js
> Contract interface bytes input

- package.json
- yarn.lock
- remove unused and unmaintained ual package
> fix: remove unused ual package dependency

- src/antelope/mocks/AccountStore.ts
- src/antelope/mocks/EVMStore.ts
- src/antelope/wallets/authenticators/EVMAuthenticator.ts
- src/assets/icon--warning.svg
- src/boot/errorHandling.js
- src/components/LoginModal.vue
- yarn.lock
> Switch network prompt

- src/components/ContractTab/GenericContractInterface.vue
Fixes the Bug: https://testnet.teloscan.io/address/0x8Fd5Dfa85b82C32467AF607c2F663A94fB85f56e#contract The write functions appear to work in the explorer but the read functions produce an error e is not a function
test: https://deploy-preview-561--testnet-teloscan.netlify.app/address/0x8Fd5Dfa85b82C32467AF607c2F663A94fB85f56e#contract
test some other contracts with custom abi and some erc20
> revert handling of custom abi

- src/layouts/MainLayout.vue
- Adjusted background gradients and circles
- Adjusted header size to fixed height
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have added appropriate test coverage
- …
> Enhance background in teloscan redesign

- src/css/app.scss
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have added appropriate test coverage
-   [x] I have updated relevant documentation and/or opened a separate issue to cover …
> added box shadow override to q-card--dark

- src/components/AddressMoreInfo.vue
- src/components/AddressOverview.vue
- src/components/ContractMoreInfo.vue
See issue
-   [x] I have updated relevant documentation and/or opened a separate issue to cover the updates (Issue URL: )
> fix: address info cards style update

- src/components/BlockTable.vue
- src/components/Health/Endpoints.vue
- src/components/Health/Monitor.vue
- src/components/InternalTransactionTable.vue
- src/components/Token/ApprovalList.vue
- src/components/Token/HolderList.vue
- src/components/Token/NFTList.vue
- src/components/Token/TokenTable.vue
- src/components/TransactionTable.vue
- src/components/TransferTable.vue
- src/pages/AccountPage.vue
Notes:
- health endpoint top table width adjusted to page width
- Token table doesn't require skeleton loading
-   [ ] I have added appropriate test coverage
-   [ ] I have updated relevant documentation and/or opened a separate issue to cover the updates (Issue URL: )
> feat: transaction table skeleton loading

- src/components/TransactionOverview.vue
- src/i18n/de-de/index.js
- src/i18n/en-us/index.js
- src/i18n/es-es/index.js
- src/i18n/fr-fr/index.js
- src/i18n/pt-br/index.js
- src/pages/TransactionPage.vue
When you go to the transaction page with an invalid transaction hash now it shows a notification message saying the transaction was not found.
https://deploy-preview-620--teloscan-redesign.netlify.app/tx/0x6d06aa07637ea762f372cfeb37cf083bbd38ad299d7f2f422240a9cbc2b02aa4
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new …
> #597 | Transaction page notifies when the transaction was not found

- src/lib/contract/FragmentParser.js
> Improve transactions loading performance

- src/pages/home/HomeLatestDataContainer.vue
Layout bug on Brave where data containers overflow
- styling should be maintained on chrome, brave, firefox for all table and data containers
> data container overflow

- src/components/Transaction/LogsViewer.vue
- src/lib/contract/FragmentParser.js
- Go to this [transaction page](https://deploy-preview-655--dev-mainnet-teloscan.netlify.app/tx/0xc0fa80353b457cd1c6f0e6dd1527f7208a305b041d7a1636ac36232e56fd62c7)
- click on Logs tab, wait for it to load
- go back to overview tab
- go for second time to Logs Tab
- It should load normally (even faster)
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the …
> #653 - Bugfix - log spinner on transaction page

- src/components/Transaction/InternalTxns.vue
- src/pages/TransactionPage.vue
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage
-   [ ] I have updated relevant documentation and/or opened a separate issue to cover …
> #650 | spinner of internal transaction tab of failed transaction never stops

- src/components/BlockTable.vue
- src/components/NftTransfersTable.vue
- src/components/TransactionTable.vue
- src/components/TransferTable.vue
- src/i18n/en-us/index.js
- src/pages/AccountPage.vue
- src/types/Pagination.ts
- src/types/index.ts
[Link](https://deploy-preview-649--teloscan-redesign-mainnet.netlify.app/address/0x61cCeF8277A6Ec2984af9d75366ed14F52f4B7F6?tab=erc721txns)
Instead of creating a new component for the new NFT tab, this PR adds two separate tabs for erc-712 and erc-1155 transfers to reuse a pre-existing component that was adjusted to avoid using the old ContractManager and take the data directly from the API response, which is significantly faster.
- Go and visit [this address](http://localhost:8080/address/0x61cCeF8277A6Ec2984af9d75366ed14F52f4B7F6?tab=erc721txns)
- Explore the ERC transfer tabs
[telosca--method-lazy-loading.webm](https://github.com/telosnetwork/teloscan/assets/4420760/c461e510-6e12-4b5a-ab31-1d1a532e6f14)
-   [x] I have commented my …
> #581 | Address page nft transfers tabs

- src/pages/home/HomeInfo.vue
This PR adds a better approach for the initial loop for querying the TLOS price and Marketcap.
- go to home page
- open the console log to see the errors
- wait around 20 seconds or less and you will see that the prices "stops loading" and shows -- instead.
The reality is that we are still updating the data but avoiding that situation that we have before.
- …
> #662 | bug the price fetching has no timeout

- src/components/Token/HolderList.vue
This PR fixes the balance display
- go to this [holders tab section](https://deploy-preview-689--dev-mainnet-teloscan.netlify.app/address/0x8f7D64ea96D729EF24a0F30b4526D47b80d877B9?tab=holders)
- see the balance display
> #685 | contract page holders tab balances formatting

- src/components/Transaction/InternalTxns.vue
- src/lib/contract/ContractManager.js
- src/pages/TransactionPage.vue
This PR fixes two problems that show up as infinite loadings. Both cases are explained in the issues themselves.
- https://deploy-preview-705--teloscan.netlify.app/tx/0x263fd4bf5ac9d237207436df4574bd55fee159b107f3240967e7a5e86d894a6b
- https://deploy-preview-705--testnet-teloscan.netlify.app/tx/0x263fd4bf5ac9d237207436df4574bd55fee159b107f3240967e7a5e86d894a6b
> Fixes for infinite loadings Transaction Page

- src/components/TransactionAction.vue
- src/components/TransactionOverview.vue
- src/lib/transaction-utils.ts
This PR redesigns the transaction action field on the transaction page.
**Note: ** in some cases the name of the method is not correctly displayed but this is an indexer issue [reported here](https://github.com/telosnetwork/teloscan-indexer/issues/231)
- https://deploy-preview-720--testnet-teloscan.netlify.app/tx/0x894856a2d54192478b97eda98dd8583d8f95ab64306f5dff0a15214726bed7e0
- https://deploy-preview-720--testnet-teloscan.netlify.app/tx/0xfb6786247ac7492d977ca9e9ddc3f4368dcf7217e1745a62e2bc13f0b4594557
- https://deploy-preview-720--dev-mainnet-teloscan.netlify.app/tx/0xcf81195f47229767c965fdb5206581558bc2a8c1e6bb956c3c5a6abddf78299c
- https://deploy-preview-720--dev-mainnet-teloscan.netlify.app/tx/0xc07c79425a099ad243b8c3e31c0a30561d3ada94e2108ed118a3361fe4e366f6
> #564 | redesign of transaction action field

- src/components/TransactionTable.vue
This is a hotfix for the NaN Age ago issue
- https://deploy-preview-738--teloscan.netlify.app/address/0xA0fB8cd450c8Fd3a11901876cD5f17eB47C6bc50
> #737 | hotfix - Age ago

- src/components/TransactionAction.vue
- src/components/TransactionOverview.vue
The TransactionAction component was re-implemented into several cases to display differently according to each case.
- Function call ([0x2bb80b11259c18abbefb22a49fd3cde1a1b455819b72ce719da5c53b912b761d](https://deploy-preview-742--dev-mainnet-teloscan.netlify.app/tx/0x2bb80b11259c18abbefb22a49fd3cde1a1b455819b72ce719da5c53b912b761d))
- TLOS transfer ([0xd4c5d3ed2f2d481d1a77819041a9f62405a7cc9f6350e12a47f26793a492afb3](https://deploy-preview-742--dev-mainnet-teloscan.netlify.app/tx/0xd4c5d3ed2f2d481d1a77819041a9f62405a7cc9f6350e12a47f26793a492afb3))
- Contract Creation ([0x0996cd9aa2dcee1ff2992f7b98b5c4c0e670e6e8c0c80cbaedcdd6e2df679c4e](https://deploy-preview-742--dev-mainnet-teloscan.netlify.app/tx/0x0996cd9aa2dcee1ff2992f7b98b5c4c0e670e6e8c0c80cbaedcdd6e2df679c4e))
> #739 | TransactionAction cases: Function call, TLOS transfer, Contract Creation

- src/components/AddressField.vue
**Fixes #786** 
https://github.com/user-attachments/assets/b06106cb-c192-4849-8692-01bd7366154d
https://github.com/user-attachments/assets/1b34c0db-7bcf-4af4-b2b2-3e5ce77d1b81
https://github.com/user-attachments/assets/6f1ccaba-cda0-4c71-97ee-37dace4fbf6f
> always show /address url instead of /token

- src/pages/export/ExportPage.vue
- yarn.lock
Updates web3.js
ejs
and
braces
> Chore deps

- package.json
- yarn.lock
This PR fixes a file conflict on dev/master branches merge
> solving conflicts with yarn.lock

- src/components/TransactionTable.vue
- yarn.lock
Fixes #839 
- Fixes wrong query in transactions page filtered by block
> Release Candidate

- src/pages/home/HomeInfo.vue
read #851. The limit was set to 1 instead of 0.
> #851 | fetchTotalTransactions function fixed on home page

- src/components/TransactionTable.vue
- src/pages/home/HomeLatestTransactions.vue
Fixes https://github.com/telosnetwork/teloscan/issues/856
> Dev to Master - Early transactions

- src/lib/contract/ContractManager.js
The null address list cache has been removed. Now, we always rely on the cache populated by content from the contracts section of each query to the indexer API. If an address is not in the cache, it is treated as a normal address, and no additional query is made to the API.
1 - To test this first you need to go to the [website deployment](https://deploy-preview-867--dev-mainnet-teloscan.netlify.app).
2 - Then open the Dev tools (F12) and go to Applications Tab, Section Storage and press "Clear Site Data" button
3 - Change to Network Tab and clear all (optional)
4 - Search for 0x0e79065B5F11b5BD1e62B935A600976ffF3754B9 and go to address page
5 - You should not see additional calls to `/v1/contract/{address}`
6 - Then go to Transactions Page (on top menu, under Blockchain section)
7 - …
> #860 | Contract Manager improvement

- src/css/app.scss
- src/css/components/_notification.scss
The colors were adjusted for dark mode
> #802 | notify dialogs with better look

- src/components/AddressField.vue
The component AddressField had a bug showing a contract icon for normal addresses. This PR fixes that problem.
https://deploy-preview-893--dev-mainnet-teloscan.netlify.app/tx/0x7faa27582b4b267e1df9d87ee1cb323461878dbf3e1d218d39d7b7098fab2af9?network=telos-evm
> #891 | AddressField fixed (contract icon on normal address)

- src/components/AppSearch.vue
This PR restores the last and better version of the search bar component.
> #895 | restore last version of search bar component

- src/boot/core.ts
- src/lib/multichain-utils.ts
This PR includes:
- the code from this PR: https://github.com/telosnetwork/teloscan/pull/887
- the code from this PR: https://github.com/telosnetwork/teloscan/pull/903
- a wrap for the problem of turning back to the old "redirect to network website" type of link
https://deploy-preview-907--dev-mainnet-teloscan.netlify.app/
https://deploy-preview-907--teloscan-stage.netlify.app/
> #884, #902 | multichain resolution (second try)

- src/config/chains/telos-zkevm-testnet/index.ts
Just changed the ID for the new zkEVM deployment
https://deploy-preview-1000--zkevm-testnet.netlify.app/
> #999 | zkevm changed the id so config file should be updated

- solidity/WrappedTelos/zkEVM/README.md
- solidity/WrappedTelos/zkEVM/WETH.sol
- solidity/WrappedTelos/zkEVM/metadata.json
- src/config/chains/index.ts
- src/config/chains/telos-zkevm-testnet/index.ts
This PR contains the configuration for the new zkEVM deployment with ETH as main coin on the chain.
It also adds the Wrapped Ether Contract configuration deployed on the address `0x6F222704E3DDc4F482423a7E54f84E0c30dF9da1`
https://deploy-preview-1002--zkevm-testnet.netlify.app/
https://deploy-preview-1002--zkevm-testnet.netlify.app/address/0x6F222704E3DDc4F482423a7E54f84E0c30dF9da1
> #999 | zkevm changed the id so config file should be updated  ether
