telosnetwork/teloscan

src/pages/Endpoints.vue

use parent element that's compatible with quasar theme toggling

fix: dark toggle for endpoints page

---

src/pages/Transaction.vue

This PR addresses https://github.com/telosnetwork/teloscan/issues/72
The page needed a few updates to the grid structure to prevent layout issues on xs-md screens. click [here](https://github.com/telosnetwork/teloscan/pull/74/files?diff=split&w=1) to view changes with ws characters hidden--much of the changes are indentation only

Fix Transaction page grid blowout 

---

src/components/AddressField.vue
src/components/CopyButton.vue
src/pages/Address.vue

Addresses #60 
In this PR:
- adds in a new component to handle text copy on click
- places copy text button on Address page
- adds in hover text for context on the existing `contract` icon (which indicates that a particular address is a smart contract) on the transactions table 
Testing notes:
- go to http://localhost:8081/address/0xfda16932cd56b9dcab6877df96c3a6bbc6cb33c0
- hover mouse over the little paper icon next to a name in the "To/Interacted With" column
- text "Contract" should appear on hover
- click into an account, e.g. http://localhost:8081/address/0x3d2c6bced5f50f5412234b87ff0b445aba4d10e9
- without clicking on the page, paste into a text field (eg. address bar, blank document)
- your clipboard contents should be whatever you last copied
- hover on the copy icon
- text …

Address Page | Add copy address button

---

src/components/ContractTab/FunctionInterface.vue

Addresses #102 
- go to https://deploy-preview-103--testnet-teloscan.netlify.app/address/0xb13d91d5d76b75f3f66aa9b3dcb049bf5bfab97e/
- click Contract, Write, and scroll down to `_startLottery` 
- enter random integers for fields `_endTime`, `_priceTicketInTelos`, `_discountDivisor`, and `_treasuryFee`
- enter any array of ints, eg. `[1, 2, 3, 4, 5, 6]` to the field `_rewardsBreakdown`
- method should fire and result in an error beginning with `Result (): cannot estimate gas` (indicating method was executed with correct data type but invalid values were passed
- try entering any other format, e.g. the incorrect number of args, `[1, 2, 3]` or `1, 2, 3` or `gewegdg34t324tgg`
- method should fire and display an error beginning with `Result (): invalid value for array`
- console error log …

Bugfix | Fix handling of uint256[] contract args

---

README.md
src/components/DateField.vue
src/pages/Transaction.vue

The date field presently overflows on the transaction page, causing whitespace to trigger the tooltip & allow toggling of the date field format
- run `yarn dev`
- go to any transaction page, eg. http://localhost:8080/tx/0xfc37ae7c127c0cf6550d62cef7e06f06f5c020f191fcb38c8d353473e1e4448f
- hover your cursor over the date field
- a tooltip should appear
- click the date field
- the format of the date should change
- hover to the right of the date field
- no tool tip should appear
- click to the right of the date field
- the date format should not change

#67 | Fix TX page date field width

---

quasar.conf.js
src/components/ContractTab/FunctionInterface.vue
src/components/ContractTab/function-interface-utils.js

This PR adds in some functionality as a stopgap until function interfaces are overhauled in #104. Currently, several types of ABI function types are not parsed correctly, leading to errors (see Issue for more info)
- adds support for `address`, `address[n?]`, `bool`,  `bool[n?]` , and `string`
- adds support for fixed vs unbounded arrays for above types as well as `uint256`, eg. `uint256[3]` is not equivalent to `uint256`
- adds warning for inputs corresponding to unimplemented types, so the user is aware of current limitations
- adds rudimentary error message & prevents method execution if supported input type has invalid value
- adds hint (in the form of placeholder text) indicating what a correct value should look like
- run `yarn dev`
- copy this mock ABI, created to test each type of …

#171 | readwrite interface doesnt handle arrays properly

---

package.json
src/boot/api.js
src/components/ConnectButton.vue
src/store/general/actions.js
src/store/general/getters.js
src/store/general/mutations.js
src/store/general/state.js
yarn.lock

Mobile clients do not inject `ethereum` into the `window` object, so effectively Ethereum is not supported in these cases. This PR adds a check to determine if ethereum is supported; if not, the login modal deeplinks to the MetaMask app.
This PR also converts `ConnectButton.vue`s template away from Pug
**Setup**
- run `yarn install && yarn dev`
**Regression Test**
- go to http://localhost:8080 in your desktop browser (which should have the MetaMask (hereafter, _MM_) extension installed)
- click the _Connect Wallet_ button
- you should see the text "MetaMask" below the fox logo
- the MM extension should pop a window prompting you to sign in
**Mobile** 
- go to your machine's IP on your phone/tablet, which is printed in the console when you run yarn dev, eg. `192.168.1.420:8080`
- tap the …

#202 | Fix MetaMask login for mobile clients

---

src/pages/AccountAddress.vue

This PR ensures that the address page (and route) displays a checksum address rather than lowercase/arbitrary casing. It does so replacing the route with checksum address immediately on page load.
- go to an address page with a lowercase address, e.g. https://deploy-preview-268--benevolent-tapioca-f74277.netlify.app/address/0xdbb168a87b6c6c88b8f0f3172c8cb929cfd53265
- you should be instantly redirected to the checksum version of the URL (the URL should have mixed case letters - e.g. it should start with `0xDbb` rather than `0xdbb`)
- click the copy button next to the address in the header
- paste the address somewhere
- the copied address should be checksum
- …

#90 | Checksum on address page

---

src/components/ContractTab/FunctionInterface.vue

This PR adds in detection for contract interface results to see if they are an address, and if so, render a link to their address page
- go to /address/0xc9e2af6d4efea2bddc2e836f79272b367fad1712#contract
- click on 'Read'
- scroll to the function called `owner`
- execute the function
- you should see "Result (address): 0x3b946C2C84a316Fe8821D1662b83AF5521537943"
- the address should link to the address page
- execute the `name` function
- you should see "Result (string): Aurora Name Service (.aurora)" with no link
-   [x] Any dependent changes have been …

#266 | Make contract interface results links for addresses

---

src/components/Transaction/ERCTransferList.vue
src/pages/Transaction.vue

Fixes transfers not showing up on the main transaction page in some specific cases (ie: contract deploy + mint)
-   [x] Transactions that deploy a contract then transfer token should show the transfers

fixed missing contract case on ERCTransfer component

---

src/layouts/MainLayout.vue

This PR modifies the site's appearance if on testnet, so it is immediately obvious to users whether they are on main- or testnet
- look at the deploy previews for [mainnet](https://deploy-preview-271--teloscan.netlify.app/) and [testnet](https://deploy-preview-271--testnet-teloscan.netlify.app/)
- main should look the same
- testnet should say "testnet" on the logo and have a different background color
-   [x] I …

#177 | Top-level Testnet indication

---

src/components/LoginModal.vue
src/components/header/AppHeader.vue
src/components/header/HeaderSearch.vue
src/components/header/LoginStatus.vue
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/pages/staking/StakeForm.vue
src/pages/staking/StakingStats.vue
src/pages/staking/WithdrawPage.vue

This PR merges all together: the Spanish and English translations along with the new Header code being translated as well. 
- The structure of the files `src/i18n/en-us/index.js` and `src/i18n/es-es/index.js` should be identical
- When you explore the site with the browser console opened you should see no warning about any missing i18n variable
- No hardcoded texts should be present on the code (other than those files)
-   [x] I have checked my code and corrected any …

Merging all together: English, Spanish, and Header translation

---

src/components/header/LoginStatus.vue

The text was not showing because of a typo in the variable name
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file
-   [ ] I have created a new issue with the required translations for the currently supported languages

fixing variable typo

---

src/boot/i18n.js
src/components/ContractTab/FunctionInterface.vue
src/components/header/AppHeader.vue
src/components/header/LanguageSwitcherModal.vue
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/pages/staking/StakeForm.vue
src/pages/staking/UnstakeForm.vue

This PR adds a language switcher to the header, as well as fixes a couple missing translations
Big thanks to @Viterbo for the js to make the language switcher work
**Broken translations**
- log in
- go to https://deploy-preview-318--teloscan-stage.netlify.app/staking
- enter any amount into the staking form
- click "Stake"
- all localizations in the confirmation modal should look good
- go to https://deploy-preview-318--teloscan-stage.netlify.app/staking#unstake
- enter any amount into the unstake form
- click "Unstake"
- all localizations in the confirmation modal should look good
**Language switcher**
- on both mobile and desktop:
- click Advanced on the site header
- click Language
- a language switcher modal should come up 
- select a different language
- app should reload with new …

#313 | Header language switcher

---

src/components/header/AppHeader.vue
src/components/header/HeaderSearch.vue
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/pt-br/index.js

fixes a couple issues with the header, see issue for details
**App name on mobile**
- on a mobile device, go to https://deploy-preview-341--teloscan-stage.netlify.app/
- you should see "Teloscan" in the header
- click search icon
- "teloscan" should hide
- on a desktop device, go to https://deploy-preview-341--teloscan-stage.netlify.app/
- appearance should be unchanged
**testnet indicator**
- go to https://deploy-preview-341--teloscan-stage.netlify.app/
- switch to light mode
- testnet indicator on logo should look nicer (added border radius, some padding)
**advanced icon**
- on a desktop device, go to https://deploy-preview-341--teloscan-stage.netlify.app/
- click the `<>` icon next to the advanced menu item
- dropdown should appear (on master branch, this does not work currently)
- …

#337 | Header updates

---

src/components/TransactionTable.vue

The current solution for the transaction table pagination although it works is not the best solution. This PR implements the same solution made for the [Internal Transaction Table](https://github.com/telosnetwork/teloscan/pull/346).
- Go to [this page](https://deploy-preview-351--teloscan-stage.netlify.app/)
- navigate to page 3
- navigate away from the table (like an address of staking section)
- press the browser's back button 
- you should see page 3
- refresh the page
- you should see page 3
-   [x] Any dependent changes have been merged and …

changing pagination using history.pushState for $router.push

---

src/components/InternalTransactionTable.vue
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/pt-br/index.js
src/pages/AccountAddress.vue
src/router/routes.js

This PR adds a new tab on the account page to show the same transaction pagination but focused on showing the internal transactions for each parent transaction.
As default behavior, the internal transactions data is visible for all transactions but the user can close and reopen the section for each transaction individually using a switcher on the right of the transaction header.
- Normal navigation
- Go to [this address account page](https://deploy-preview-346--dev-mainnet-teloscan.netlify.app/address/0xa30b5e3c8Fee56C135Aecb733cd708cC31A5657a)
- Press the Internal Transactions Tab
- You should see the first page of transactions (currently all of them have zero int-trxs)
- change the page until you see a transaction with some internal transactions
- close ad reopen the content section of …

New tab for show internal transactions history for a given address

---

src/components/header/AppHeader.vue

The advanced menu would sometimes not open on click because the click listener was on the incorrect element; if the cursor was on the edge of the menu element, clicking it would have no effect even though the hover style would appear.
- first reproduce the issue in prod: go to https://teloscan.io
- hover over the Advanced menu element in the header and click the corner of the highlighted box
- see that the menu does not appear
- go to https://deploy-preview-366--dev-mainnet-teloscan.netlify.app/
- follow the same steps to reproduce
- the advanced menu should appear on click
-   [x] My changes …

#354 | Fix header advanced menu

---

.github/workflows/main.yml
README.md
package.json
src/components/ContractTab/GenericContractInterface.vue
src/lib/ContractManager.js
src/pages/AccountAddress.vue
yarn.lock

- Upgrades web3 version from 1.x to 4.x
- Fixes sourcify link in generic contract template
- Updates README and include note about updated required Node version
- Updates CI yaml node version
1. Contract interaction should be consistent with deploy previews in #419 
2. 'Click Here' link should redirect to sourcify for unverified contracts
- this includes a new required Node version 16
-   [x] I have removed any …

upgrade web3 package

---

.github/workflows/main.yml
README.md
package.json
src/components/ContractTab/FunctionInterface.vue
src/components/ContractTab/GenericContractInterface.vue
src/lib/ContractManager.js
src/pages/AccountAddress.vue
yarn.lock

This fixes  #418 where users are not being able to interact with smart contracts using their Anchor Wallet
Users should be able to interact with smart contracts using their Native wallets and native linked EVM addresses.

made contract instance raw so we can access properties

---

src/pages/HealthPage.vue
src/router/routes.js

see issue 
- visit https://deploy-preview-453--teloscan.netlify.app/endpoints
- should redirect to https://deploy-preview-453--teloscan.netlify.app/health (/endpoints -> /health)

fix: redirect /endpoints to /health

---

package.json
src/antelope/mocks/AccountStore.ts
src/antelope/mocks/AntelopeConfig.ts
src/antelope/wallets/init.ts
src/components/LoginModal.vue
src/components/header/AppHeader.vue
yarn.lock

The PR includes three different parts:
- removal of the legacy code (related to the login process and not part of the Antelope Wallets solution)
- partial migration of some Antelope events (onLoggedIn and onLoggedOut)
- refactor the previous login and logout process by subscribing to those events
With those changes, now the Antelope Wallets are the only way to log in and out, and that makes the internal subscription to the provider's `accountChange` event, to actually work. Because now using the Antelope library to log in to the newly detected account, will end up in a handler subscribed to the onLoggedIn event, and therefore the site will reflect the new state.
See the video: [Metamask-change-account--Teloscan.webm](https://github.com/telosnetwork/teloscan/assets/4420760/2b2e775d-0e34-4f8 …

handle wallet address change gracefully do not require reload

---

src/components/ContractTab/function-interface-utils.js
src/components/inputs/BytesArrayInput.vue
src/i18n/de-de/index.js
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/fr-fr/index.js
src/i18n/pt-br/index.js
test/components/ContractTab/function-interface-utils.test.js

The bytes input is currently implemented incorrectly, expecting a value like `'[ab, cd, ef]'` when it should be expecting a string like `'0xabcdef'` for bytes arrays. This PR fixes that issue.
- go to https://deploy-preview-504--dev-mainnet-teloscan.netlify.app/address/0x46893403C4aD778d7FDA0CdFCe355a0A7dba3333#contract
- go to the `Write` tab
- scroll down and expand the method `estimateSendFee`
- enter the following values: 
```
_dstChainId: 102    
_toAddress: 0x0000000000000000000000000000000000000000000000000000000000000001
_amount: 1
_useZro: false
_adapterParams: 0x00010000000000000000000000000000000000000000000000000000000000030d40
```
- you should be able to execute the method and get a result
- in the `_toAddress` field, which is a fixed-length bytes input, enter a valid bytes …

#501 | Fix bytes input

---

src/App.vue
src/antelope/mocks/AccountStore.ts
src/antelope/mocks/ChainStore.ts
src/antelope/mocks/EVMStore.ts
src/antelope/wallets/authenticators/EVMAuthenticator.ts
src/antelope/wallets/authenticators/InjectedProviderAuth.ts
src/antelope/wallets/authenticators/WalletConnectAuth.ts
src/components/LoginModal.vue

This PR enables analytics for teloscan when logging in
For reference, here are the event IDs used: 
```
export const TELOS_ANALYTICS_EVENT_IDS = {
loginStarted: 'GXQ8FOAU',
loginSuccessful: 'B1BZBK5R',
loginSuccessfulMetamask: 'JQTSKEFY',
loginFailedMetamask: 'PKHBRTYV',
loginSuccessfulSafepal: 'WV5OSVMQ',
loginFailedSafepal: '7WSBR8LA',
loginSuccessfulOreId: 'HUDIQQEK',
loginFailedOreId: 'AJXWOXWJ',
loginFailedWalletConnect: 'ZVKXJDK1',
loginSuccessfulWalletConnect: 'AQMOMICF',
};
```
- this PR will need to be tested locally. run `git fetch --all && git checkout 507-login-analytics && yarn && yarn dev`
- open `ChainStore.ts` and paste this at the top of the function: `console.log('tracking fathom event with ID ' + params.id);`
- open your browser to http://localhost:8080
- open your …

#507 | Add analytics (teloscan)

---

src/App.vue
src/antelope/mocks/AccountStore.ts
src/antelope/mocks/ChainStore.ts
src/antelope/mocks/EVMStore.ts
src/antelope/wallets/authenticators/EVMAuthenticator.ts
src/antelope/wallets/authenticators/InjectedProviderAuth.ts
src/antelope/wallets/authenticators/WalletConnectAuth.ts
src/components/LoginModal.vue

Fathom Analytics

---

src/antelope/mocks/ChainStore.ts
src/antelope/mocks/chain-constants.ts
src/antelope/wallets/authenticators/InjectedProviderAuth.ts
src/antelope/wallets/authenticators/OreIdAuth.ts
src/antelope/wallets/authenticators/WalletConnectAuth.ts

This PR updates how Fathom analytics is used to avoid a deprecated method, and adds support for tracking Brave wallet logins
- this PR will need to be tested locally in the **brave browser**. run `git fetch --all && git checkout 511-analytics-updates && yarn && yarn dev`
- open `ChainStore.ts` and paste this at the top of the function `trackAnalyticsEvent`: `console.log('tracking fathom event with name ' + eventName);`
- open your browser to http://localhost:8080
- open your browser dev console
- in the dev console, filter messages by `fathom` (so you can see fathom logging easier)
- if you are using brave browser ad blocking or any ad blocker, disable it
- if you have already connected your Metamask to localhost, disconnect it from the metamask menu
- click "Connect wallet" in Teloscan
- …

#511 | Update teloscan analytics

---

src/antelope/mocks/AccountStore.ts
src/antelope/mocks/EVMStore.ts
src/antelope/wallets/authenticators/EVMAuthenticator.ts
src/assets/icon--warning.svg
src/boot/errorHandling.js
src/components/LoginModal.vue

This PR includes a new function `assertNetworkConnection` for the account store that will prompt the user to change the network and block the code until the user either refuses or accepts and effectively changes the network. 
It also removes the code responsible for warning the user that a network switch has been detected because we don't need it if we are only displaying data. However, when the user tries to sign a transaction we need to explicitly check the network and prompt the user to change it.
- Login using Metamask
- Once logged, open Metamask, change the network and come back to the web app
- you should not get any notification
- you should be able to explore all sections and your data should be correct
- got to any transaction page and try to perform one: e.g. liquid staking …

prompt switch network only before transaction signing

---

src/css/global/_mixins.scss
src/pages/BlockListPage.vue
src/pages/TransactionsPage.vue

This PR includes a simple mixin to use for body page so every content would behave the same way
- Try to reproduce the bug #569 and check is not present anymore in [this deployment](https://deploy-preview-571--teloscan-stage.netlify.app/)
-   [x] I have included all english text to the translation file and/or created a new issue with the required …

#569 - Fix horizontal scroll on mobile

---

src/css/components/_notification.scss

Link: https://deploy-preview-580--teloscan-stage.netlify.app/
This PR forces black to be the text color on notifications.
- Try to reproduce the bug described in #579

#579 | bugfix - Notification text not visible on dark mode

---

src/components/BlockOverview.vue
src/components/BlockTable.vue
src/pages/home/HomeLatestBlocks.vue
src/pages/home/HomeLatestDataContainer.vue
src/pages/home/HomeLatestDataTableRow.vue
src/pages/home/HomePage.vue
src/types/BlockData.ts

This PR adds the HomeLatestBlocks component holding the last produced blocks.
- go to [this link](https://deploy-preview-575--teloscan-redesign.netlify.app/)
- wait until you see the component loaded
- you should see the last 6 blocks displaying:
- number (blockHeight)
- number of transactions
- gas used
-   [x] I have included all english text to the …

#532 | Homepage latest blocks

---

src/components/AddressQR.vue

[Test link](https://deploy-preview-626--teloscan-redesign-mainnet.netlify.app/address/0xA10165F5fAe1975Badb16B1d9efC62F5b6aceb8c)
This PR adds a workaround to the problem of the QR popup scrolling the page when it's closed.
I couldn't determine the cause of this problem so I couldn't fix the problem. The page still scrolls down when the popup is closed but now is immediately restored. However, you can notice a no-desired block effect.
-   [x] I have checked my code and …

#625 | Closing qr popup scrolls the page on chrome

---

src/components/BlockOverview.vue
src/css/app.scss
src/css/global/_colors.scss
src/css/global/global-index.scss
src/pages/home/HomeInfo.vue
src/pages/home/HomeLatestBlocks.vue
src/pages/home/HomeLatestDataContainer.vue
src/pages/home/HomeLatestDataTableRow.vue
src/pages/home/HomeLatestTransactions.vue

- The parameter noEmpty=true was added to the block query. When this parameter works, the frontend will adapt on its own.
- The number of the last mined block is now a link to the block page.
- The margins of the latest-data box were adjusted.
- On the block page, the number was not being fetched correctly. It showed a 0, and now it displays the correct value.
-   [x] I have removed any unnecessary console …

More things fixed

---

src/components/BlockTable.vue
src/pages/BlockListPage.vue

- default to only display non-empty blocks
- add table toggle to include empty blocks

default to non-empty blogs, add toggle to include

---

src/components/header/AppHeaderLinks.vue

This PR put Testnet links on the app header when running the app on Testnet. This involves the wallet and the bridge.
- Go to [this link (Testnet)](https://deploy-preview-660--teloscan-redesign.netlify.app/)
- click on Wallet/Stake
- it should redirect you to the Testnet version of the wallet
- click on Bridge link
- it should redirect you to the Testnet version of the bridge
-   [x] I have removed any …

#646 | walletstaking link for testnet links to mainnet wallet

---

src/layouts/MainLayout.vue

This PR sets the dark mode as the default
- Open [This link.](https://deploy-preview-683--testnet-teloscan.netlify.app/)
- clean the cache
- refresh the page
- the Light/Dark mode should be the same as your browser settings

#673 | Light mode by default

---

solidity/README.md
solidity/SimpleCounterManager/README.md
solidity/SimpleCounterManager/SimpleCounterManager.sol
solidity/SimpleCounterManager/SimpleCounterManager_metadata.json
src/components/AddressField.vue
src/components/TransactionOverview.vue

This PR changes the way we display transactions for Contract Deployments
**Note**: This PR also introduces a new folder to start adding all solidity contracts that we may need to test any functionality. This way we can control and recreate all the situations we need and reuse old examples. 
- https://deploy-preview-695--testnet-teloscan.netlify.app/tx/0x5df4473bd7ae4304280c794f8147b53c9a83a26b8396ad04dc78f035dbd6eddd
- https://deploy-preview-695--testnet-teloscan.netlify.app/tx/0x9ce49f2b30520a6327e4aa4971e597b9823543333e6d85f5b2abf86558ac296b

#672 | Show deployed contract in contract deployment transactions

---

src/components/Transaction/ERCTransferList.vue

This PR fixes the broken section of erc20 transfers in a Transaction
- go and see [this transaction](https://deploy-preview-690--teloscan.netlify.app/tx/0x37a18e059f6765dc4d2e5bd24e0cbe3f2a4e752934522a6f02a292ec023f8913?tab=transactions)
- you should see the ERC20 Tranfers

#687 | transaction page erc20 transfers on overview tab are missing

---

src/components/NftTransfersTable.vue
src/components/Transaction/ERCTransferList.vue

This PR fixes the display of the value for the ERC20 Transfers tab.
- https://deploy-preview-694--dev-mainnet-teloscan.netlify.app/address/0xA25bc8c1e230a476cB00f2e9c93ffC2D4e163dc5?tab=tokentxns
- https://deploy-preview-694--dev-mainnet-teloscan.netlify.app/address/0x9728f7772f95a7346c22C831Ff6bAC565662d8dA?tab=tokentxns
**Note:** There is a problem with the symbol that replicates in two different places. The problem is described in this separate issue: https://github.com/telosnetwork/teloscan/issues/693

#686 | address page erc20 transfers tab value formatting

---

src/antelope/mocks/AccountStore.ts
src/antelope/mocks/AntelopeConfig.ts
src/boot/errorHandling.js
src/boot/fathom.js
src/i18n/en-us/index.js
src/router/routes.js

This PR changes the function to manage error messages:
- First, it tries to see if the error code is something known to be treated in a special way (like when you cancel from the wallet).
- If not, then it tries to extract the reason or the message from the error object. It uses the deepest option in the case of having multiple message attributes
- Finally, it tries to 
Change OOOPS to Error

#684 | improve error reporting notification

---

src/pages/AccountPage.vue

This just adds a `border-radius:100%` to the token icon in the account page header

make token icon circles consistently in account page

---

src/components/NftTransfersTable.vue
src/components/TransactionTable.vue
src/components/TransferTable.vue
src/css/global/_mixins.scss
src/i18n/de-de/index.js
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/fr-fr/index.js
src/i18n/pt-br/index.js
src/lib/transaction-utils.ts
src/types/NftTransfers.ts
src/types/index.ts

This PR adds the direction column to the transaction table only if filtered by an account.
- https://deploy-preview-713--testnet-teloscan.netlify.app/address/0xa30b5e3c8Fee56C135Aecb733cd708cC31A5657a?p=1&rowsPerPage=10&sort=DESC

#657 | restore inout fields on transaction table

---

src/components/NftTransfersTable.vue
src/components/TransferTable.vue
src/css/global/_mixins.scss
src/i18n/de-de/index.js
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/fr-fr/index.js
src/i18n/pt-br/index.js
src/lib/transaction-utils.ts
src/types/NftTransfers.ts
src/types/index.ts

This PR adds the SELF-direction sign to show those transfers to the same account.
- https://deploy-preview-711--testnet-teloscan.netlify.app/address/0xa30b5e3c8Fee56C135Aecb733cd708cC31A5657a?tab=tokentxns
- https://deploy-preview-711--teloscan.netlify.app/address/0xa30b5e3c8Fee56C135Aecb733cd708cC31A5657a?tab=erc721txns
- https://deploy-preview-711--teloscan.netlify.app/address/0xD478589b68e162B1D5B3e57323d0b280A96896Bf?tab=erc1155txns

#699 | showing self transfers as such

---

src/components/NftTransfersTable.vue

This PR repairs de display of the value being transferred to ERC transfer tabs
- https://deploy-preview-712--teloscan.netlify.app/address/0x13B745FC35b0BAC9bab9fD20B7C9f46668232607?tab=tokentxns

#708 | reparing value display in transfers table

---

src/components/TransactionTable.vue

This PR makes the Txn fee column header shorter.
- https://deploy-preview-729--teloscan-stage.netlify.app/address/0x62FDf8A96FD134fa7A22b7D3A6D4D5411D063432

#726 | Txn Fee header is shorter

---

src/components/AddressField.vue
src/pages/AccountPage.vue
src/router/routes.js

This PR adds the new token route and adjusts the link presented on the AccountField component to be /token instead of /address in the case of a token address.
- https://deploy-preview-728--teloscan.netlify.app/txs
- https://deploy-preview-728--teloscan.netlify.app/token/0xa3b4AeE7B43B2Fb390420c411ec180B0ae87E9da

#724, #725 | adding token route

---

src/components/AddressField.vue
src/components/AddressOverview.vue
src/components/ContractMoreInfo.vue
src/components/InternalTransactionFlatTable.vue
src/components/MethodField.vue
src/components/NftTransfersTable.vue
src/components/Token/ApprovalList.vue
src/components/Token/HolderList.vue
src/components/Token/TokenGridElement.vue
src/components/Token/TokenTable.vue
src/components/Transaction/ERCTransferList.vue
src/components/Transaction/TLOSTransferList.vue
src/components/TransactionAction.vue
src/components/TransactionField.vue
src/components/TransactionOverview.vue
src/components/TransactionTable.vue
src/pages/AccountPage.vue
src/router/routes.js
src/store/general/actions.js
src/store/general/getters.js
src/store/general/mutations.js
src/store/general/state.js

- Incorporates the flat view for Internal transactions
- change the implementation for highlights using store instead of emitting events.
- Change decimals default to be dynamic and not fixed as before.
- https://deploy-preview-723--dev-mainnet-teloscan.netlify.app/address/0x8C74aaD7a7daC4feF064145eAe2bcbF97c3547f7?tab=internaltx
- https://deploy-preview-723--dev-mainnet-teloscan.netlify.app/address/0x339d413CCEfD986b1B3647A9cfa9CBbE70A30749?tab=internaltx
- https://deploy-preview-723--dev-mainnet-teloscan.netlify.app/address/0x4b4c4a6e760FDEa078efC6BEa046946b639BdDEA?tab=internaltx

#573 | Internal Transactions Flat

---

src/components/ContractTab/ContractInterface.vue

This PR forces the labels to use ellipsis when the space is not wide enough.
- https://deploy-preview-743--dev-mainnet-teloscan.netlify.app/address/0x7138B62539C410E14E6471c22EC739F6A6985E58?tab=contract

#722 | fix labels when overflow

---

src/boot/errorHandling.js
src/components/Token/NFTList.vue
src/i18n/de-de/index.js
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/fr-fr/index.js
src/i18n/pt-br/index.js

In the cases where the image of the NFT is embedded, there is no way to show it in a different browser tab. So clicking on it downloads the image. This PR adds a confirmation dialog before actually downloading the image.
- go to [this link](https://deploy-preview-745--dev-mainnet-teloscan.netlify.app/address/0xe7209d65c5BB05Ddf799b20fF0EC09E691FC3f11?tab=nfts)
- scroll to find the NFT named _lock # 48_
- click on the image
- you should see a popup confirmation dialog that disappears after 5 seconds
- only if you confirm, the images downloads

#740 | add confirmation step before downloading image from nft

---

src/components/TransactionTable.vue
src/types/Pagination.ts

This PR modifies the way we paginate content on the transaction page. Now we use the `key `parameter when before we were using _offset_ parameter.
- Go to [this page](https://deploy-preview-744--dev-mainnet-teloscan.netlify.app/txs?p=1&rowsPerPage=10&sort=DESC)
- open dev tools (F12) and go to Network
- filter by text: "transactions"
- you should see a first call using key=0 and limit=1
- you should see a second normal call using the correct limit
- go to next page
- you should not see a query with key=0 this time
- you should see a query using the previous "next" parameter
- Go to the [first page](https://deploy-preview-744--dev-mainnet-teloscan.netlify.app/txs?p=1&rowsPerPage=10&sort=DESC) again
- wait 5 min and refresh the page
- you should see no changes
- keep this tap open (let's …

#606 | transaction pagination based on key

---

src/components/AddressField.vue
src/components/InternalTransactionFlatTable.vue
src/components/Token/TokenTable.vue
src/components/ValueField.vue
src/components/header/AppHeaderLinks.vue
src/css/app.scss
src/css/global/_mixins.scss
src/i18n/de-de/index.js
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/fr-fr/index.js
src/i18n/pt-br/index.js
src/lib/contract/ContractManager.js
src/lib/transaction-utils.ts
src/pages/AccountPage.vue
src/pages/InternalTrxPage.vue
src/router/routes.js

This PR continues the work on this [other PR](https://github.com/telosnetwork/teloscan/pull/723) and adds a specific page to display a paginated table of internal transactions for the given address. It is possible to expand and collapse all internal transactions as in the previous implementation, but this information is shown in a flat mode in this new component.
- https://deploy-preview-731--dev-mainnet-teloscan.netlify.app/txsinternal?a=0x8a8AFe1A74a1cc8babD78c8eB138aF589123adD2
- https://deploy-preview-731--dev-mainnet-teloscan.netlify.app/txsinternal

#567 | contract internal transactions page

---

src/components/TransactionTable.vue

This PR fixes the block filter when querying the transactions for a specific block.
- Block Transactions: https://deploy-preview-748--teloscan-stage.netlify.app/block/298942836?tab=transactions
- All transactions: https://deploy-preview-748--teloscan-stage.netlify.app/txs

fixing block filter on transactions query

---

src/lib/contract/ContractManager.js

There was a variable being used before checking if it was null. That is checked now which avoids the bug.
go to https://deploy-preview-756--testnet-teloscan.netlify.app/tx/0x4c072f0cf146c23e69d722876ace7181847fb07c36d81a72329c3f49bef7030e

bugfix - avoid using null contract

---

src/antelope/mocks/AccountStore.ts
src/components/LoginModal.vue
src/components/TransactionTable.vue

In the previous version, after a not finished attempt to login using Metamask, the user experimented a constant and annoying behavior of the Metamask poping up each time the page gets refreshed.
This PR fixes this problem.
- If you have your Metamask open, change the Network to Ethereum. If not, just let it close.
- Go to [this url](https://deploy-preview-750--dev-mainnet-teloscan.netlify.app/)
- press "Connect Wallet"
- Select Metamask but refuse to connect (cancel the process).
- the website should return to normal disconnected state
- refresh the page (F5)
- Metamask should not popup to ask you to login.

#715 | fix Metamask popup problem

---

src/components/ContractTab/FunctionInterface.vue
src/components/InternalTransactionFlatTable.vue

This PR contains fixes for two issues.
This PR adds a workaround for the NaN age issue but should [be fixed on the backend](https://github.com/telosnetwork/teloscan-indexer/issues/234) since it can explode elsewhere.
This PR also adds a fix for the bug on the boolean queries not showing the false value. That is fixed and now it shows true and false values.
https://deploy-preview-764--dev-mainnet-teloscan.netlify.app/txsinternal
https://deploy-preview-764--dev-mainnet-teloscan.netlify.app/address/0x75ab3C5bDd841BE0922a19139782f7650305dC05?tab=contract
- Go to Contract tab, press ABI from JSON, and insert this ABI into the input field:
```json
[
{
"inputs": [],
"name": "isGood",
"outputs": [
{
"internalType": "bool",
"name": "",
"type": "bool"
}
],
"stateMutability": "view",
"type": …
```

#737 | workaround for the NaN age + fix false values not showing

---

src/components/Transaction/TransactionInputViewer.vue
src/components/TransactionOverview.vue
src/components/TransactionTable.vue
src/i18n/de-de/index.js
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/fr-fr/index.js
src/i18n/pt-br/index.js
src/lib/transaction-utils.ts
src/pages/TransactionPage.vue

[Deployment](https://deploy-preview-759--dev-mainnet-teloscan.netlify.app/)
This PR includes the solution for two of the three views that the new TransactionInputViewer component should offer. The Default view requires a refinement of the algorithms, so it was separated in this issue (#762) and will be scheduled apart.
The two views implemented are:
- Original: is the input as plain text
- Decoded: Is the Table with all parameters' types and values.
- https://deploy-preview-759--dev-mainnet-teloscan.netlify.app/tx/0x3c81e5a0636da5d29f2eed4e0487dca3e6f36fe341821882c7d351f2de1bf48e
- https://deploy-preview-759--dev-mainnet-teloscan.netlify.app/tx/0x5abb5f2c39a12ccc0cd96c879d3ccd3d756ce7bfca369d72b655349d57de61a6

#747 | decode trx input to show contract function call

---

src/components/ImagePopup.vue
src/components/Token/NFTList.vue
src/css/app.scss
src/i18n/de-de/index.js
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/fr-fr/index.js
src/i18n/pt-br/index.js

This PR adds a new component to preview the image in a popup dialog. This dialog can be resized and also includes a button to download the image.
- https://deploy-preview-758--dev-mainnet-teloscan.netlify.app/address/0xe7209d65c5BB05Ddf799b20fF0EC09E691FC3f11?tab=nfts
In this link you can see tree cases in the same page:
- A normal size NFT:
- A really small one:
- And a big image case:
You can also change the image preview size on the table row by clicking the "Media"  title at the top of the column.

#740 | Popup Image viewer for NFTs

---

src/components/ContractTab/ContractInterface.vue
src/components/ContractTab/FunctionInterface.vue

This PR removes the need to be logged to execute the contract's read functions.
- Go to [this link](https://deploy-preview-773--teloscan-stage.netlify.app/token/0xa9991E4daA44922D00a78B6D986cDf628d46C4DD?tab=contract)
- make sure you are not logged
- Go to the Contract tab, then read tab
- try to read approvals with any pair of addresses.
- you should be able to execute the function without being logged.

#772 | No need to be logged to read from contracts

---

src/components/InternalTransactionFlatTable.vue
src/i18n/de-de/index.js
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/fr-fr/index.js
src/i18n/pt-br/index.js

Fixes #787 
Currently the "Direction" Column isn't capitalized, and has no translations unlike the other columns in the transactions table:
Production example: https://www.teloscan.io/address/0x9c5ebCbE531aA81bD82013aBF97401f5C6111d76?tab=internaltx
Fix here: https://deploy-preview-788--dev-mainnet-teloscan.netlify.app/address/0x9c5ebCbE531aA81bD82013aBF97401f5C6111d76?tab=internaltx

Add translations and column name for "Direction"

---

src/components/ContractTab/FunctionInterface.vue
src/components/ContractTab/FunctionOutputViewer.vue
src/types/TransactionQueryData.ts
src/types/index.ts

This PR implements a new FunctionOutputViewer component to show function responses much more legibly, similar to a JSON format. It also makes every address present in the response as a browseable link.
- go to [this contract read section](https://deploy-preview-779--testnet-teloscan.netlify.app/address/0x08B10679B2Cf7A244293fD670CDf0EF5F2982588?tab=contract&subtab=read)
- query any function
- see the response with a JSON-like format

new FunctionOutputViewer component to show function responses

---

src/pages/export/ExportPage.vue

Las minute bugfix: The CSV export button was never enabled.

BugFix: export csv button fixed

---

src/components/TransactionTable.vue

- Update getPath function to calculate currentKey based on initialKey and page
- Modify parseTransactions to use last item's ID for pagination.key
- Remove unused 'page' variable in parseTransactions function
- Improve consistency when navigating between pages and changing items per page
This PR addresses pagination inconsistencies on the Transaction page by modifying the logic for setting and updating pagination parameters and handling transaction data fetching more efficiently. It ensures the pagination state is maintained correctly across different interactions and edge cases.
- Go to the [Teloscan deployment](https://deploy-preview-798--teloscan-stage.netlify.app/)
- Navigate to the Transaction page
- Verify pagination works correctly:
- Change page numbers
- Adjust items per page
- …

Fix pagination inconsistencies in TransactionTable

---

src/components/ContractTab/ContractTab.vue
src/components/Transaction/InternalTxns.vue
src/components/Transaction/LogsViewer.vue
src/css/components/_notification.scss

This PR fixes several style problems like the card missing behind the verified contract content and some padding in several places on the transaction page.
- Check [the log tab on the transaction page](https://deploy-preview-811--dev-mainnet-teloscan.netlify.app/tx/0x573792a31be28765e4a4514cb94fdcf76fdcfccdd1fce42cc0932503cd07c9ab) and toggle Human Readable   
- Check the card on the [verified contract tab](https://deploy-preview-811--dev-mainnet-teloscan.netlify.app/address/0xf774801c9f1b11e70966CE65EC7f95d7730F380d?tab=contract)   
- Check the notification messages on Dark mode: #802

#810, #706, #802 | Several style fixes

---

src/components/TransactionAction.vue
src/lib/data-export-utils.ts
src/lib/transaction-utils.ts

This PR correctly distinguishes between a [Contract Creation transaction](https://www.teloscan.io/tx/0x732d95e9854ca426bc042479327bd4f88f2eb1a885e5bd69259695b80a65b7a3), a [normal TLOS transfer](https://www.teloscan.io/tx/0x3622917b7cac6bd052755feeeae6046921849213484837b3051995a376a2985b) and a [TLOS transfer to null address with parameters](https://www.teloscan.io/tx/0x0d5177bc7bb83e4ee84a17421e74d32d4b26c3d17eaca20d30adfaf26780aa39)
In the case of a contract being created, it replaces the receiver (to) field with the contract address.
- check [normal TLOS transfer](https://deploy-preview-809--dev-mainnet-teloscan.netlify.app/tx/0x3622917b7cac6bd052755feeeae6046921849213484837b3051995a376a2985b)  
- check [TLOS transfer to null address with …

#806 | Contract Creation transaction fixed

---

src/components/Token/TokenGridElement.vue

Broken token cards were restyled. Now they look better and use the whole space available.
Activate the grid mode on the Tokens tab
https://deploy-preview-826--dev-mainnet-teloscan.netlify.app/address/0xa30b5e3c8Fee56C135Aecb733cd708cC31A5657a?tab=tokens

#817 | Broken token cards were restyled.

---

src/components/AppSearch.vue

At the beginning, the Indexer API was returning each address twice (one in lowercase and the other one in checksum format). That is why we were filtering only the checksum formatted addresses. But now it only returns the lowercase format, so no address results are shown because all of them were filtered out. Now that is fixed, and no filtering is performed at all.
1 - go to [this deployment link](https://deploy-preview-838--dev-mainnet-teloscan.netlify.app/)
2 - enter: 0x31644692d2c2b7228f9763416e7612451F69009e or any other valid address
3 - see one result

checksum acceptance criteria for filtering address removed

---

src/components/AddressOverview.vue
src/components/AppSearch.vue
src/lib/contract/ContractManager.js

The problem in #844 was caused by a null value stored in my local cache. Fortunately, it affected only me but it would eventually affect others with time. So the code causing the bug was fixed (regardless of the cache values).
The problem with the double result was fixed by restoring the filter that was previously removed.
Also, there was an unnecessary ValueField component that was not used and was causing a warning on the console. That component was removed.

Hotfix for #845 and #844

---

src/components/TransactionTable.vue

The Transactions Page and Address Page on the Transactions tab use the same component TransactionsTable with different columns depending on the context. This PR fixes the amount of loading columns for that Transaction Page In which the direction column is not used.
https://deploy-preview-855--testnet-teloscan.netlify.app/txs
https://deploy-preview-855--testnet-teloscan.netlify.app/address/0x5E1BE25D4A2De0083012f1B5A8030a7023fFA5bc

#847 | amount of loading columns for transactions page fixed

---

src/pages/home/HomeLatestTransactions.vue

The query for the last 6 transactions was adjusted to include the metadata necessary to display the contracts names avoiding the following queries for each address involved.

#853 | home page includes the contract metadata on the last 6 trx query

---

src/components/TransactionTable.vue

There was an overflow in the calculation of the key to use on the query when trying to access the last (first in time) page of transactions. It was fixed to equal the page size in case of overflow.
1. Go to [Transaction Page](https://deploy-preview-861--dev-mainnet-teloscan.netlify.app/txs)
2. Scroll down to pagination buttons
3. click on the last page
4. see the last block number

#856 | Transactions page pagination fixed to show the fery first page

---

src/lib/contract/ContractManager.js

The current implementation has a minimal difference. Now, each time we need to display an address, we take the possible contract metadata from the local cache, delegating to the indexer API the responsibility of populating that cache on each query.
You can test this now on the mainnet on the USDT holders page:
- Go to https://deploy-preview-850--dev-mainnet-teloscan.netlify.app/address/0x975Ed13fa16857E83e7C493C7741D556eaaD4A3f
- Open the developer tools (F12) in the Network section and clear everything.
- Go to the Holders tab.
- Confirm that there's no extra query to fetch each address.
- Navigate through the pages and ensure there's no extra query for unknown addresses.

#816 | change the strategy to only fetch contracts from cache

---

src/components/AppSearch.vue
src/components/AppSearchResultEntry.vue
src/components/MethodField.vue
src/lib/blockies/blockies.ts
src/pages/AccountPage.vue

- The icon for the Address page was changed for a blockie-icon in case of a contract or normal address. In case of a ERC-20 it shows the normal token Icon.
- The field width for the function name was raised to show more complete names.
- Address: https://deploy-preview-868--dev-mainnet-teloscan.netlify.app/address/0x77F0Db20D64051D081170e95fC0d0F5aa40C249c
- Contract: https://deploy-preview-868--dev-mainnet-teloscan.netlify.app/address/0x3B7023f3C99EAe2FA0AaeB9490A78d5D98a24148
- Token: https://deploy-preview-868--dev-mainnet-teloscan.netlify.app/address/0xB4B01216a5Bc8F1C8A33CD990A1239030E60C905?tab=transactions

#829 | address page has blockie icon (based on address)

---

src/components/AddressMoreInfo.vue
src/i18n/de-de/index.js
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/fr-fr/index.js
src/i18n/pt-br/index.js
src/pages/AccountPage.vue

This PR does not fix the main problem. It only adds a new case in which the consulted address has no transaction registered in history. But the main problem remains and it's on the server side.
The API is returning no transaction history for this particular address.
https://deploy-preview-876--dev-mainnet-teloscan.netlify.app/address/0xe0740E654B33550712E192c00C857D64Ce675Af3

#875 | adding the case for no transaction history on address page

---

src/components/ContractTab/FunctionInterface.vue
src/components/inputs/TupleStruct.vue
src/lib/function-interface-utils-ts.ts
src/lib/function-interface-utils.js
src/types/FunctionInterfaces.ts
src/types/index.ts

Until now, the only way to input tuple parameters was through the `TupleStructInput` component, which is a simple input, and the user has to deal with the complexity of the specific format for each case. Now, using `TupleStruct` the user can navigate through the complexity of the value structure and fill each property input with a simple value.
Go to the Write section of this contract to test some tuple functions
https://deploy-preview-872--dev-mainnet-teloscan.netlify.app/address/0xc5F13247b1a2547Fd0f6C7696695cDFeB003027c?tab=contract&subtab=write

#824 | New user friendly component for tuple inputs

---

src/components/AddressOverview.vue

The balance line was displayed as a column, making the icon and balance text aligned vertically instead of horizontally. This PR fixes that and also makes a forgotten hard-coded TLOS symbol to be dynamic, depending on the selected network.
https://deploy-preview-894--dev-mainnet-teloscan.netlify.app/address/0x45cB7B68F22A8CeD95305e21F451BFD0f499242e?network=telos-evm

#892 | fixing icon-balance row

---

src/components/header/AppHeaderLinks.vue
src/components/header/AppHeaderTopBar.vue
src/layouts/MainLayout.vue
src/lib/multichain-utils.ts

This PR is included in [this other PR](https://github.com/telosnetwork/teloscan/pull/904)
This PR fixes not only the low-resolution buttons to switch between networks but also refactors the whole implementation from the original component code to a utils-multichain-specific shared script that incorporates reacting and updating the network parameter. The default value is based on the `NETWORK_EVM_NAME` environment variable.
... to be continued

#902 | in low resolutions the switch network component uses the old buttons

---

src/components/TransactionTable.vue

The key computation was fixed to establish a correct initial key from which to navigate.
Now the first page queried includes the last transaction registered by the indexer.
https://deploy-preview-914--dev-mainnet-teloscan.netlify.app/
[teloscan---first-transactions-page-fixed.webm](https://github.com/user-attachments/assets/a8e86fbc-0c9a-4dc6-9809-f7b09605b945)

First page of Transactions Page was skipping last transactions

---

src/components/AppSearch.vue
src/pages/home/HomeInfo.vue

Small patch for this branch: Removed a query with an incorrect parameter that was causing responses with over 1K results.

removing a bug

---

src/components/Token/TokenList.vue
src/lib/contract/ContractManager.js

A few changes were made to ensure we always cache contracts that may come in any response. Also, put the crashing code inside a try-catch statement to avoid infinite loading.
https://deploy-preview-936--dev-mainnet-teloscan.netlify.app/address/0xbccc4b4c6530F82FE309c5E845E50b5E9C89f2AD?tab=tokens

#935 | Fixing broken token balances section for address page

---

src/App.vue
src/config/chains/telos-evm-testnet/index.ts
src/config/chains/telos-evm/index.ts
src/config/chains/telos-zkevm-testnet/index.ts
src/core/chains/EVMChainSettings.ts
src/core/mocks/ChainStore.ts
src/core/types/ChainSettings.ts
src/core/types/NetworkConfig.ts
src/core/types/Theme.ts

We need to customize the explorer tab text for each network. So in the special case of zk we can shgow "Teloscan zkEVM Testnet"

#928 | Customizing the browser tab title for each network

---

src/components/TransactionTable.vue

This PR enhances the way the component MethodField obtains the function's name. If the contract parsing fails, it falls back to the abi section of the response which may contain a function signatures map.
https://testnet.teloscan.io/address/0x689F601fA828C089B1DC1D7530595684fF9f84D6?tab=transactions
https://deploy-preview-951--testnet-teloscan.netlify.app/address/0x689F601fA828C089B1DC1D7530595684fF9f84D6?tab=transactions

#946 | Display the function names when possible on transactions table

---

src/components/Transaction/ERCTransferList.vue
src/components/Transaction/TLOSTransferList.vue
src/components/TransactionOverview.vue
src/pages/TransactionPage.vue

This PR makes sure that no duplicated ERC20 transfer is shown In the Transaction page overview
Original problem: https://www.teloscan.io/tx/0x77c29b71aa69a5756c4c2f00530e8f02376175d7102a9d084237f9782e9ea113?tab=overview

#948 | token swaps duplicated in transaction view

---

src/pages/TransactionPage.vue

This PR fixes the problem of the page not updating while you are standing on the Transactions page, specifically on Internal Transactions tab and you search for another transaction and click on the result.
Now the page changes the tab to Overvew and updates all data.
- Go to https://deploy-preview-961--dev-mainnet-teloscan.netlify.app/tx/0xa3c1244a7fd6e188ad1002d6331ba811f6d1bc4f09384856133d8f243daecf7c?tab=internal
- Be sure to be on the Internal Transaction Tab
- Search for trx: 0xc58e32fb95a54c5f6522f950855e8c153d6204ff6bbd383663cae115a86b7f62
- Click on result
- The page data should be updated

#957 | fix Transaction page tab update after another trx search

---

src/components/EmptyTableSign.vue
src/components/InternalTransactionFlatTable.vue
src/components/NftTransfersTable.vue
src/components/Token/NFTList.vue
src/components/TransactionTable.vue
src/i18n/de-de/index.js
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/fr-fr/index.js
src/i18n/pt-br/index.js

This PR creates a new component to display a nice sign saying there's no matching data for the empty table. It was used in all tables on the website.
https://deploy-preview-965--dev-mainnet-teloscan.netlify.app/address/0x6A8cC581c663Af575162dBDcAAd53fAC1e5A5478

#942 | Display clear empty state for addresscontract transaction tables

---

src/components/TransactionTable.vue
src/core/chains/EVMChainSettings.ts
src/lib/contract/ContractManager.js
src/lib/contract/FragmentParser.js

The original problem for this error is the indexer returning null values as function names in the abi section. This PR handles this situation better and prints a more descriptive, clear warning text.
A new issue was created for the indexer to table this situation: https://github.com/telosnetwork/teloscan-indexer/issues/322

#969 | unsupported fragment error better handled

---

src/components/Token/HolderList.vue

This PR adds a loading spinner while waiting for the indexer to respond to the health request to see if the version is the minimum required. After getting the version, it decides if it can show the table with the data or the text sign explaining the minimum version required is not fulfilled.
https://deploy-preview-973--testnet-teloscan.netlify.app/accounts

#972 | HoldersList showing a spinner until being ready

---

src/config/chains/telos-evm/index.ts
src/core/mocks/EVMStore.ts

The name and RPC link were fixed from `Telos EVM` to `Telos EVM Mainnet` and from `https://rpc.telos.net:433/evm` to `https://rpc.telos.net`
However, with these changes, it is not possible to eliminate the warnings that Metamask displays even using the site's official links that list the known EVM blockchains.
- Remove Metamask from browser
- Install a fresh instance of Metamask
- go to this [PR deployment for Mainnet](https://deploy-preview-979--dev-mainnet-teloscan.netlify.app/)
- be sure to be logged out
- try to log in again
- You should see the Metamask warning sign when trying to register the `Telos EVM Mainnet`
On a fresh installation of Metamask, I tried to register the Telos EVM Mainet blockchain from the official site (https://chainlist.org/chain/40) and I still got the …

#890 | Fix the rpc and name for first time registering the chain on Metamask

---

src/App.vue
src/config/chains/telos-evm-testnet/index.ts
src/config/chains/telos-evm/index.ts
src/config/chains/telos-zkevm-testnet/index.ts
src/core/mocks/ChainStore.ts
src/core/types/NetworkConfig.ts

This PR adds a new parameter to set the maximum number of seconds to consider the indexer up to date. The new parameter is called `secondsBehindThreshold`

#980 | implement chain specific indexer outdated threshold

---

src/lib/contract/ContractManager.js

Unused parameters were removed from the contract metadata request
- Go to https://deploy-preview-990--dev-mainnet-teloscan.netlify.app/address/0xc96afc666A4195366a46E4ca8C4f10f3C39Ee363
- open dev tools (F12) in Network tab
- filter by "/v1/contract/"
- See no extra parameters in the request

#989 | removing deprecated parameters from contract metadata request

---

src/components/header/AppHeaderBottomBar.vue
src/components/header/AppHeaderLinks.vue
src/css/app.scss
src/layouts/MainLayout.vue

This PR moves all Safari-specific styles under the .is-safari class once detected by javascript code.
This prevents those specific styles from affecting the website running on other browsers.
- Test the navbar menus on Chrome or Firefox
- See no changes
- Test the nabvar menues on Safari
- See the specific style changes being applied.

#622 | Move Safari navbar styles under safari specific class

---

src/components/ContractTab/FunctionInterface.vue
src/components/ContractTab/FunctionOutputViewer.vue

When introducing the new `FunctionOutputViewer` component, all responses were formatted as JSON, which was unnecessary for simple-type responses. This issue has been fixed, and simple-type responses are now displayed directly without using JSON, resulting in a more compact display.
https://deploy-preview-994--testnet-teloscan.netlify.app/address/0x08B10679B2Cf7A244293fD670CDf0EF5F2982588?tab=contract&subtab=read

#881 | make simple responses no json formated

---

src/i18n/de-de/index.js
src/i18n/en-us/index.js
src/i18n/es-es/index.js
src/i18n/fr-fr/index.js
src/i18n/pt-br/index.js
src/pages/export/ExportPage.vue
src/types/window-eth.d.ts
src/types/window.d.ts

This PR implements client-side validations for export range inputs to mirror server constraints. It validates both date and block ranges to ensure they do not exceed the maximum allowed interval (one year for dates and the equivalent in blocks) and displays error messages when the inputs are invalid, while also disabling the download button to prevent 500 errors.

#975 | Implement Client-Side Export Range Validations

---

src/pages/export/ExportPage.vue

Changed color to use primary colors on csv export page.

#1007 | addapting colors to primary on csv export page for readability
